port: 3000
pygments: true
safe: false
lsi: false
url: http://arthur.gonigberg.com
permalink: /:year/:month/:day/:title
excerpt_separator: <!--more-->
include: ['.well-known']

markdown: rdiscount
rdiscount:
  extensions: ['footnotes']
